float64 target_x
float64 target_y
float64 target_theta
float64 tolerance_xy
float64 tolerance_theta
---
bool success
string message
float64 final_x
float64 final_y
float64 final_theta
---
float64 current_x
float64 current_y
float64 current_theta
float64 distance_remaining
float64 estimated_time
